### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [matveyrb/Du#1]
1. Директорию `.idea`, в которой находятся настройки вашей локальной среды разработки, лучше добавлять в `.gitignore`.
2. А почему тип возвращаемого значения `Any`? [link](https://github.com/matveyrb/Du/blob/9349bc55dabb098dfd9c8aa90b9fcba73825dd03/src/main/kotlin/DuStart.kt#L25)
3. А зачем выше принтить то же самое? [link](https://github.com/matveyrb/Du/blob/9349bc55dabb098dfd9c8aa90b9fcba73825dd03/src/main/kotlin/DuStart.kt#L32)
4. Размер файла в символах может не соответствовать размеру файла в байтах, т.к. зависит от кодировки. [link](https://github.com/matveyrb/Du/blob/9349bc55dabb098dfd9c8aa90b9fcba73825dd03/src/main/kotlin/Du.kt#L14)
5. Параметр `h` лучше сделать enum. [link](https://github.com/matveyrb/Du/blob/9349bc55dabb098dfd9c8aa90b9fcba73825dd03/src/main/kotlin/Du.kt#L23)

Здесь я просто скопирую задание, чтобы было проще к нему отсылать.

du
Вывод на консоль размера указанного файла(-ов) или каталога(-ов) из файловой системы:
fileN задаёт имя файла, размер которого нужно вывести. Таких параметров может быть несколько.
Флаг -h указывает, что размер следует выдавать в человеко-читаемом формате: в зависимости от размера файла результат выдается в байтах, килобайтах, мегабайтах или гигабайтах и дополняется соответствующей единицей измерения (B, KB, MB, GB). Если данный флаг не указан, размер должен печататься в килобайтах и без единицы измерения.
Флаг -c означает, что для всех переданных на вход файлов нужно вывести суммарный размер.
Флаг --si означает, что для всех используемых единиц измерения следует брать основание 1000, а не 1024.

Command line: du [-h] [-c] [--si] file1 file2 file3 … 

На вход может быть передано любое количество имён файлов. Все флаги совместимы друг с другом. Размер каталога равен сумме размеров всех входящих в него файлов и каталогов. Если на вход передаётся имя, не соответствующее существующему файлу, следует вместо результата выдать ошибку. Возвращаемое значение программы в случае успеха равняется 0, в случае ошибки 1.

Кроме самой программы, следует написать автоматические тесты к ней.

Есть следующие несоответствия с заданием:
1. При выводе не указываются единицы измерения.
2. При выводе информации по нескольким файлам не выводятся имена файлов.
3. Если в качестве файла у вас указать каталог, то работать оно не будет.
4. Утилита не возвращает код завершения, а должна 0 или 1.
5. Тесты должны также проверять указанную единицу измерения и название файла/каталога, к которому это относится.

**Comment by Saloed** [comment]
1. Для получения размера файла лучше всего использовать [`Files.size`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#size-java.nio.file.Path-)
2. Если `h` сделать `enum`, то код станет чуть лучше. А так, ничего особо не изменится. Кстати, не очень понятно, почему у вас `h` задаётся аргументом утилиты? В аргументах утилиты `h` -- это просто флаг. `h`, на основании которого вы приписываете `MB/GB...` должен вычисляться на основе размера файла. [link](https://github.com/matveyrb/Du/blob/708e0dbcf7d8f712b5a057a42dd2e4d843db1910/src/main/kotlin/Du.kt#L42)

**Comment by matveyrb** [comment]
Хотелось узнать по поводу флага h, если он используется, нужно выводить конкретное количество, например:
1кб 5б, или можно округлить?
Загрузил изменения с вычислением размера файла.

**Comment by Saloed** [comment]
1. Если указан флаг `h`, то да, нужно округлить. Число знаков можете взять любое, но лучше не больше 3. 
2. Директория может быть указана и не только на 0 позиции. [link](https://github.com/matveyrb/Du/blob/5d7021b6e67a6f23dd709bb7cb84cfd6cf970ca7/src/main/kotlin/Du.kt#L53)
3. Вообще, не очень понятно, зачем это делать. `walkFileTree`, который вы используете для подсчёта размера, и так обойдет все дерево с учётом поддиректорий. [link](https://github.com/matveyrb/Du/blob/5d7021b6e67a6f23dd709bb7cb84cfd6cf970ca7/src/main/kotlin/Du.kt#L53)
4. Если переменная используется только в теле цикла, то её лучше там и объявлять. [link](https://github.com/matveyrb/Du/blob/5d7021b6e67a6f23dd709bb7cb84cfd6cf970ca7/src/main/kotlin/Du.kt#L59)
5. Лучше складывать значения для суммы без приведения к нужному формату. Так результат получится более точным. [link](https://github.com/matveyrb/Du/blob/5d7021b6e67a6f23dd709bb7cb84cfd6cf970ca7/src/main/kotlin/Du.kt#L74)


Если вас всё ещё нет в чате группы, то напоминаю, что 1.04  последнее занятие, на котором можно показать 2 задание. Следующее занятие будет через 2 недели, и там уже будет штраф за просрочку.

**Comment by matveyrb** [comment]
Так вы же сказали дедлайн по 2 заданию 4.04 а не завтра, я не знал об этом, не уверен что успею

**Comment by Saloed** [comment]
До 4.04 можно будет замечания доделать.

**Comment by Saloed** [comment]
1. А зачем эту переменную заводить? [link](https://github.com/matveyrb/Du/blob/7002dd8116df4599d62f41d5d939c96ba019aa99/src/main/kotlin/DuStart.kt#L34)
2. Вот [этот](https://github.com/matveyrb/Du/blob/master/src/main/kotlin/Du.kt#L72-L88) кусок кода и [этот](https://github.com/matveyrb/Du/blob/master/src/main/kotlin/Du.kt#L96-L111) очень похожи. Надо их как-то объединить. 
3. Замечания 2 и 3 из предыдущего списка. 
4. А почему `Path` `nullable`? [link](https://github.com/matveyrb/Du/blob/7002dd8116df4599d62f41d5d939c96ba019aa99/src/main/kotlin/Du.kt#L12)
5. Есть [способ попроще](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#toPath()) получить `Path` из `File`. [link](https://github.com/matveyrb/Du/blob/7002dd8116df4599d62f41d5d939c96ba019aa99/src/main/kotlin/Du.kt#L65)

**Comment by matveyrb** [comment]
Исправил "Директория может быть указана и не только на 0 позиции."
Не получается вообще без этого обойтись, надеюсь подскажете с пунктом 3.

**Comment by matveyrb** [comment]
Загрузил исправления.
По поводу пункта 3, мне удобнее использовать эту функцию потому что так в множестве iteratelist мы храним названия файлов которые хранятся в директории так как нужен же не только размер файлов но и их названия.
Я просто не могу понять зачем менять если такое решение нормально работает, если вы так не считаете то подскажите пожалуйста что мне нужно сделать конкретнее, спасибо.

**Comment by Saloed** [comment]
А зачем вам имена файлов в директории?

**Comment by matveyrb** [comment]
Загрузил исправления, извините за задержку.
Убрал функции, просто использовал библиотеку File utils для подсчета размера, понял что вы имели ввиду насчет директорий, убрал лишние строки, но так же из за тестов снова вышла проблема с выводом 0 или 1 после завершения программы, я не знаю как одновременно выводить результат завершения и одновременно передавать все в тесты, поэтому получилось вот так, в общем посмотрите и скажите что да как, спасибо

**Comment by Saloed** [comment]
1. Замечание 2 из предыдущего списка всё ещё актуально. 
2. Надо бы как-то отделить этап, где вы собираете данные о размере файлов и этап, где вы эти размеры приводите к нужным единицам измерения и выводите.
3. В тестах надо бы проверить, что именно ваша утилита выводит, а не только то, что она правильно получает размеры файлов.
4. После исправления замечания 2 и 3, проблема с возвращаемым статусом уйдёт. У вас не будет мест, где надо одновременно список размеров проверить и статус.
5. Перевод в множество [вот здесь](https://github.com/matveyrb/Du/blob/b947af4a645641bc9ce7322812df28ea232c1418/src/main/kotlin/Du.kt#L14) не гарантирует сохранение порядка, а в тестах при сравнении со списком порядок важен.

**Comment by matveyrb** [comment]
Пробовал подправить, в итоге смирился, видел в тг вы писали, согласен на 3.
Можете так же посмотреть мой курсовой проект, Backgammon.
Жду замечаний или указаний, спасибо

**Comment by Saloed** [comment]
Хорошо, тогда ваша оценка 3.
